very frist try
aws-samples/aws-cdk-examples pull request #1111
Opened 2024-12-20 13:47 UTC by mihaws

Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2024-12-27 20:55 UTC, kaiz-io requested changes

2024-12-27 20:55 UTC, kaiz-io commented on typescript/bedrock-kb-agent/lib/constructs/cloudfront-s3-website-construct.ts
> +    const s3origin = new cdk.aws_cloudfront_origins.S3Origin(this.siteBucket, {
S3Origin has been deprecated can you update to S3OriginBucket.

Also your tests are failing please fix.

2024-12-31 14:47 UTC, mihaws commented
The deprecated api was removed.
About the tests, I can run the test using
`npm run test`

in the top level of the project, all the test are running 

`
Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        252.097 s
`
do you have any specific way to start the tests, like a cicd pipeline, do I need to follow some name conventions ?

2024-12-31 16:02 UTC, kaiz-io commented
We run the following as defined in [/scripts/build-typescript.sh](https://github.com/aws-samples/aws-cdk-examples/blob/main/scripts/build-typescript.sh)

Looks like you are missing you web-app directory.

```sh
    yarn install --mutex network
    yarn build
    npm run --if-present test
```



```sh
+ npm run --if-present test
FAIL test/bedrock-kb-agent-stack.test.ts (8.458 s)
  BedrockKbAgentStack
    ✕ Cognito User Pool is created with correct name (275 ms)
    ✕ API Gateway HTTP API is created (36 ms)
    ✕ Lambda function is created with correct configuration (42 ms)
    ✕ At least one IAM policy includes required Bedrock permissions (39 ms)
    ✕ S3 bucket for knowledge base is created (38 ms)
    ✕ Bedrock Knowledge Base is created (39 ms)
    ✕ Bedrock Agent is created (46 ms)
    ✕ API Gateway routes are created (40 ms)
    ✕ Stack has the expected number of resources (41 ms)
  ● BedrockKbAgentStack › Cognito User Pool is created with correct name
    Cannot find asset at /home/runner/work/aws-cdk-examples/aws-cdk-examples/typescript/bedrock-kb-agent/web-app/dist
      192 |     }
      193 |
    > 194 |     new cdk.aws_s3_deployment.BucketDeployment(this, "DeployWithInvalidation", {
          |     ^
      195 |       sources: [
      196 |         cdk.aws_s3_deployment.Source.asset(props.webSiteBuildPath), // Main webapp from root directory
      197 |         cdk.aws_s3_deployment.Source.jsonData("config.json", amplifyConfig), // Amplify config file
      at new AssetStaging (node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2221)
      at new Asset (node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1243)
      at Object.bind (node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1562)
      at node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3870
          at Array.map (<anonymous>)
      at new BucketDeployment (node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3851)
      at new CloudFrontS3WebSiteConstruct (lib/constructs/cloudfront-s3-website-construct.ts:194:5)
      at new BedrockKbAgentStack (lib/bedrock-kb-agent-stack.ts:35:21)
      at Object.<anonymous> (test/bedrock-kb-agent-stack.test.ts:12:13)
  ● BedrockKbAgentStack › API Gateway HTTP API is created
    Cannot find asset at /home/runner/work/aws-cdk-examples/aws-cdk-examples/typescript/bedrock-kb-agent/web-app/dist
      192 |     }
      193 |
    > 194 |     new cdk.aws_s3_deployment.BucketDeployment(this, "DeployWithInvalidation", {
          |     ^
      195 |       sources: [
      196 |         cdk.aws_s3_deployment.Source.asset(props.webSiteBuildPath), // Main webapp from root directory
      197 |         cdk.aws_s3_deployment.Source.jsonData("config.json", amplifyConfig), // Amplify config file
      at new AssetStaging (node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2221)
      at new Asset (node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1243)
      at Object.bind (node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1562)
      at node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3870
          at Array.map (<anonymous>)
      at new BucketDeployment (node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3851)
      at new CloudFrontS3WebSiteConstruct (lib/constructs/cloudfront-s3-website-construct.ts:194:5)
      at new BedrockKbAgentStack (lib/bedrock-kb-agent-stack.ts:35:21)
      at Object.<anonymous> (test/bedrock-kb-agent-stack.test.ts:12:13)
  ● BedrockKbAgentStack › Lambda function is created with correct configuration
    Cannot find asset at /home/runner/work/aws-cdk-examples/aws-cdk-examples/typescript/bedrock-kb-agent/web-app/dist
      192 |     }
      193 |
    > 194 |     new cdk.aws_s3_deployment.BucketDeployment(this, "DeployWithInvalidation", {
          |     ^
      195 |       sources: [
      196 |         cdk.aws_s3_deployment.Source.asset(props.webSiteBuildPath), // Main webapp from root directory
      197 |         cdk.aws_s3_deployment.Source.jsonData("config.json", amplifyConfig), // Amplify config file
      at new AssetStaging (node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2221)
      at new Asset (node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1243)
      at Object.bind (node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1562)
      at node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3870
          at Array.map (<anonymous>)
      at new BucketDeployment (node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3851)
      at new CloudFrontS3WebSiteConstruct (lib/constructs/cloudfront-s3-website-construct.ts:194:5)
      at new BedrockKbAgentStack (lib/bedrock-kb-agent-stack.ts:35:21)
      at Object.<anonymous> (test/bedrock-kb-agent-stack.test.ts:12:13)
  ● BedrockKbAgentStack › At least one IAM policy includes required Bedrock permissions
    Cannot find asset at /home/runner/work/aws-cdk-examples/aws-cdk-examples/typescript/bedrock-kb-agent/web-app/dist
      192 |     }
      193 |
    > 194 |     new cdk.aws_s3_deployment.BucketDeployment(this, "DeployWithInvalidation", {
          |     ^
      195 |       sources: [
      196 |         cdk.aws_s3_deployment.Source.asset(props.webSiteBuildPath), // Main webapp from root directory
      197 |         cdk.aws_s3_deployment.Source.jsonData("config.json", amplifyConfig), // Amplify config file
      at new AssetStaging (node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2221)
      at new Asset (node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1243)
      at Object.bind (node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1562)
      at node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3870
          at Array.map (<anonymous>)
      at new BucketDeployment (node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3851)
      at new CloudFrontS3WebSiteConstruct (lib/constructs/cloudfront-s3-website-construct.ts:194:5)
      at new BedrockKbAgentStack (lib/bedrock-kb-agent-stack.ts:35:21)
      at Object.<anonymous> (test/bedrock-kb-agent-stack.test.ts:12:13)
  ● BedrockKbAgentStack › S3 bucket for knowledge base is created
    Cannot find asset at /home/runner/work/aws-cdk-examples/aws-cdk-examples/typescript/bedrock-kb-agent/web-app/dist
      192 |     }
      193 |
    > 194 |     new cdk.aws_s3_deployment.BucketDeployment(this, "DeployWithInvalidation", {
          |     ^
      195 |       sources: [
      196 |         cdk.aws_s3_deployment.Source.asset(props.webSiteBuildPath), // Main webapp from root directory
      197 |         cdk.aws_s3_deployment.Source.jsonData("config.json", amplifyConfig), // Amplify config file
      at new AssetStaging (node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2221)
      at new Asset (node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1243)
      at Object.bind (node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1562)
      at node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3870
          at Array.map (<anonymous>)
      at new BucketDeployment (node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3851)
      at new CloudFrontS3WebSiteConstruct (lib/constructs/cloudfront-s3-website-construct.ts:194:5)
      at new BedrockKbAgentStack (lib/bedrock-kb-agent-stack.ts:35:21)
      at Object.<anonymous> (test/bedrock-kb-agent-stack.test.ts:12:13)
  ● BedrockKbAgentStack › Bedrock Knowledge Base is created
    Cannot find asset at /home/runner/work/aws-cdk-examples/aws-cdk-examples/typescript/bedrock-kb-agent/web-app/dist
      192 |     }
      193 |
    > 194 |     new cdk.aws_s3_deployment.BucketDeployment(this, "DeployWithInvalidation", {
          |     ^
      195 |       sources: [
      196 |         cdk.aws_s3_deployment.Source.asset(props.webSiteBuildPath), // Main webapp from root directory
      197 |         cdk.aws_s3_deployment.Source.jsonData("config.json", amplif [...]

2025-01-03 13:49 UTC, mihaws commented
Thx answer Michael,
It was my bad i forgot to check the .gitignore, and there were a `dist` right at the top. 
I will fix this in the next mins and I will run the test as you suggested

2025-01-03 14:48 UTC, mihaws commented
I add the missing dirs and  run a test locally with a fresh checked branch, all tests are running 

....
 npm run --if-present test                                                                                                                                                                                                                                
....

 PASS  test/bedrock-kb-agent-stack.test.ts (272.977 s)a-powertools-3.4.0 aws_xray_sdk-2.14.0 botocore-1.35.91 jmespath-1.0.1 jsonpath_ng-1.7.0 ply-3.11 pydantic-2.10.4 pydantic-core-2.27.2 python-dateutil-2.9.0.post0 six-1.17.0 typing-extensions-4.12.2 ur
  BedrockKbAgentStack
    ✓ Cognito User Pool is created with correct name (41952 ms)
    ✓ API Gateway HTTP API is created (25198 ms)
    ✓ Lambda function is created with correct configuration (26406 ms)
    ✓ At least one IAM policy includes required Bedrock permissions (27259 ms)
    ✓ S3 bucket for knowledge base is created (25676 ms)
    ✓ Bedrock Knowledge Base is created (26277 ms)
    ✓ Bedrock Agent is created (44441 ms)
    ✓ API Gateway routes are created (26414 ms)
    ✓ Stack has the expected number of resources (25973 ms)

Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        273.034 s

2025-01-03 18:29 UTC, kaiz-io approved these changes
:rocket:

2025-01-03 18:29 UTC, merged