Added version to eks.Cluster with 1.17 as version to be compatible wi…
aws-samples/aws-cdk-examples pull request #321
Opened 2020-07-31 15:43 UTC by dnmach

…th cdk v1.55.0

Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2020-10-05 02:34 UTC, NGL321 submitted a review, later dismissed
Thanks for the fix, and sorry for the delay in review!

😸 😷

2020-10-24 20:31 UTC, shivlaks requested changes

2020-10-24 20:31 UTC, shivlaks commented on typescript/eks/cluster/index.ts
> +      version: eks.KubernetesVersion.V1_17,
there's a version key on line 22 that should have it's value updated instead of introducing a duplicate key

2021-09-28 23:58 UTC, ryparker requested changes

2021-09-28 23:58 UTC, ryparker commented on typescript/eks/cluster/index.ts
>        version: eks.KubernetesVersion.V1_16,
```suggestion
```
This is a duplicate key.

2021-09-29 00:00 UTC, ryparker commented
Changes already merged.

2021-09-29 00:00 UTC, closed without merging