feat(python): AWS SSM AutoPAtching sample
aws-samples/aws-cdk-examples pull request #441
Opened 2021-05-14 21:42 UTC by elgamala

Added AWS SSM AutoPatching sample using Maintenance window, patch group and predefined patch baseline.

Fixes #248 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2021-09-29 17:41 UTC, ryparker requested changes

2021-09-29 17:41 UTC, ryparker commented on python/systems-manager/auto_patching/README.md
> +$
```suggestion
$ pip install -r requirements.txt
```

2021-09-29 17:41 UTC, ryparker commented on python/systems-manager/auto_patching/requirements.txt
> +-e .
Can we lift the contents of `python/systems-manager/auto_patching/*` one directory to `python/systems-manager`, and get rid of the `/auto_patching` folder?

2022-09-22 17:58 UTC, indrora commented
Thank you for your contribution. Unfortunately, this PR is very old, has had no movement, and predates the launch of CDK v2. 

I'm going to close this PR for now. If you update it to use the CDKv2, please open a new PR.

2022-09-22 17:58 UTC, closed without merging