feat(python): Adding CDK example chaining S3, SNS, SQS and Lambda (Typescript)
aws-samples/aws-cdk-examples pull request #568
Opened 2021-11-17 23:32 UTC by ericglasser

Fixes [#520](https://github.com/aws-samples/aws-cdk-examples/issues/520)
---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2022-02-15 23:16 UTC, ryparker requested changes
A few suggestions before we merge. Mostly around upgrading to CDK v2 since we recommend everyone make the leap.

Thanks for contributing 🙏🏻

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/cdk.json
> +  }
```suggestion
  "context": {
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/core:stackRelativeExports": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": true
  }
```
Removed the flags that are deprecated in v2.
[v2 Feature flag docs](https://docs.aws.amazon.com/cdk/v2/guide/featureflags.html)

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/lib/s3_sns_sqs_lambda_chain-stack.ts
> +  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
```suggestion
import { App, Stack, StackProps, Duration } from 'aws-cdk-lib';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as lambdaNodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import * as lambdaEvents from 'aws-cdk-lib/aws-lambda-event-sources';
import * as snsSubscriptions from 'aws-cdk-lib/aws-sns-subscriptions';
import * as s3Notifications from 'aws-cdk-lib/aws-s3-notifications';
import { join } from 'path'

export class S3SnsSqsLambdaChainStack extends Stack {
  constructor(scope: App, id: string, props?: StackProps) {
```

Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/lib/s3_sns_sqs_lambda_chain-stack.ts
> +          retentionPeriod: cdk.Duration.days(7)
```suggestion
          retentionPeriod: Duration.days(7)
```

Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/lib/s3_sns_sqs_lambda_chain-stack.ts
> +        visibilityTimeout: cdk.Duration.seconds(30),
```suggestion
        visibilityTimeout: Duration.seconds(30),
```
Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/lib/s3_sns_sqs_lambda_chain-stack.ts
> +          }
```suggestion
            expiration: Duration.days(365),
            transitions: [
              {
                storageClass: s3.StorageClass.INFREQUENT_ACCESS,
                transitionAfter: Duration.days(30)
              },
              {
                storageClass: s3.StorageClass.GLACIER,
                transitionAfter: Duration.days(90)
              }
            ]
          }
```
Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/package.json
> +  }
```suggestion
  "devDependencies": {
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "*",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
   	"aws-cdk-lib": "*",
    "constructs": "*"
  }
```

Would you mind [upgrading this to CDK v2](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html#migrating-v2-v1-uppgrade) for consistency with the other projects we have? I've added code suggestions with all the necessary code to upgrade. It's possible I may have missed something though but let me know if you have trouble.

By the way you'll need to update the lockfile once these suggestions are accepted. Run `npm install` and commit the updated lockfile changes.

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/test/s3_sns_sqs_lambda_chain.test.ts
> +import * as cdk from '@aws-cdk/core';
```suggestion
import { Template, Match } from 'aws-cdk-lib/assertions';
import { App } from 'aws-cdk-lib';
```
Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/test/s3_sns_sqs_lambda_chain.test.ts
> +  const app = new cdk.App();
```suggestion
  const app = new App();
```
Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/test/s3_sns_sqs_lambda_chain.test.ts
> +  const app = new cdk.App();
```suggestion
  const app = new App();
```
Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/test/s3_sns_sqs_lambda_chain.test.ts
> +  const app = new cdk.App();
```suggestion
  const app = new App();
```
Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/test/s3_sns_sqs_lambda_chain.test.ts
> +  const app = new cdk.App();
```suggestion
  const app = new App();
```
Upgrade to CDK v2

2022-02-15 23:16 UTC, ryparker commented on typescript/s3-sns-lambda-chain/bin/s3_sns_sqs_lambda_chain.ts
> +const app = new cdk.App();
```suggestion
import { App } from 'aws-cdk-lib';
import { S3SnsSqsLambdaChainStack } from '../lib/s3_sns_sqs_lambda_chain-stack';

const app = new App();
```
Upgrade to CDK v2

2022-03-05 00:31 UTC, ericglasser commented
@ryparker Thank you for the review I have upgraded to CDK v2, and used your suggestions.

2022-03-09 20:50 UTC, ryparker submitted a review, later dismissed
Hey @ericglasser 👋🏻 

Thanks for making those changes. I have one suggestion on the README and another ⛏️ spacing suggestion.

I did run into an error when deploying this today:

```sh
12:47:34 PM | CREATE_FAILED        | AWS::SQS::Queue                 | deadLetterQueueId
Resource handler returned message: "Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happen
ing on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long." (RequestToken: df20a05d-43d5-5948-5ee3-b0a584e
75fd7, HandlerErrorCode: GeneralServiceException)
```

Could you see if you're able to reproduce this on your end?

2022-03-09 20:50 UTC, ryparker commented on typescript/s3-sns-lambda-chain/README.md
> +The `cdk.json` file tells the CDK Toolkit how to execute your app.
```suggestion
Ensure aws-cdk is installed and your AWS account/region is [bootstrapped](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html).

	  ```bash
	  $ npm install -g aws-cdk
	  $ cdk bootstrap
	  ```

Then build and deploy.
_You will need to have [Docker](https://docs.docker.com/get-docker/) installed and running._

	  ```bash
	  $ npm run build
	  $ cdk deploy
	  ```
```

Added some additional guidance on how to bootstrap, build, and deploy the app.

2022-03-09 20:50 UTC, ryparker commented on typescript/s3-sns-lambda-chain/lib/s3_sns_sqs_lambda_chain-stack.ts
> +export class S3SnsSqsLambdaChainStack extends Stack {
```suggestion

export class S3SnsSqsLambdaChainStack extends Stack {
```

Spacing

2022-03-30 00:35 UTC, ericglasser commented
Hey @ryparker,

Sorry for the delay I didn't get a notification for the update. I made the suggested changes and tested deploying and destroying the environment I was unable to reproduce the issue though are you still seeing it?

2022-12-19 23:21 UTC, ericglasser commented
@ryparker circling back on this, I was wondrering if you ever had a chance to review the changes?

2023-01-14 04:38 UTC, ryparker approved these changes

2023-10-01 19:08 UTC, kaizio reviewed
Fixed tests

2023-10-01 19:09 UTC, kaizio approved these changes

2023-10-01 19:09 UTC, merged