fix: Updated java/custom-resource to use non-deprecated software.amazon.awscdk.CustomResource construct
aws-samples/aws-cdk-examples pull request #759
Opened 2022-10-04 05:18 UTC by its-mirus-lu

Updated Java custom-resource example by refactoring it to use the software.amazon.awscdk.CustomResource construct. This also brings this example in line with the Typsecript example in this repo.

This update will also address bugs #746, #748

Fixes #756, #746, #748

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2023-02-17 11:12 UTC, Naumel requested changes
Hello, thank you for your contribution. A few of the comments are nit picks, but it looks like there is a case to be made for some code clean-up too.

2023-02-17 11:12 UTC, Naumel commented on java/custom-resource/lambda/custom-resource-handler.py
> +  print("create new resource with props %s" % props)
```suggestion
  print("Create new resource with props %s" % props)
```

2023-02-17 11:12 UTC, Naumel commented on java/custom-resource/lambda/custom-resource-handler.py
> +      'Response': 'You said "%s"' % message
```suggestion
      'Response': 'Resource message "%s"' % message
```

2023-02-17 11:12 UTC, Naumel commented on java/custom-resource/lambda/custom-resource-handler.py
> +  print("update resource %s with props %s" % (physical_id, props))
```suggestion
  print("Update resource %s with props %s" % (physical_id, props))
```

2023-02-17 11:12 UTC, Naumel commented on java/custom-resource/lambda/custom-resource-handler.py
> +  print("delete resource %s" % physical_id)
```suggestion
  print("Delete resource %s" % physical_id)
```

2023-02-17 11:12 UTC, Naumel commented on java/custom-resource/lambda/custom-resource-handler.py
> +  # is_ready = ...
Left over?

2023-02-18 03:57 UTC, its-mirus-lu commented on java/custom-resource/lambda/custom-resource-handler.py
> +  print("create new resource with props %s" % props)
Addressed in new commit.

2023-02-18 03:57 UTC, its-mirus-lu commented on java/custom-resource/lambda/custom-resource-handler.py
> +      'Response': 'You said "%s"' % message
Addressed in new commit.

2023-02-18 03:57 UTC, its-mirus-lu commented on java/custom-resource/lambda/custom-resource-handler.py
> +  print("delete resource %s" % physical_id)
Addressed in new commit.

2023-02-18 04:02 UTC, its-mirus-lu commented
@Naumel: I've updated the PR with your recommendations. Please have a look when you've got a moment.

2023-10-01 21:49 UTC, kaizio approved these changes

2023-10-01 21:50 UTC, merged