feat: CDK Cross Region AWS CodeArtifact Sample
aws-samples/aws-cdk-examples pull request #796
Opened 2023-01-31 19:00 UTC by kareem-rady

Added a Cross Region CodeArtifact sample utilizing CDK to deploy an upstream pipeline that packages and pushes a sample python package to another region hosted in a central Devops account and a downstream pipeline also hosted in a Devops account  that pulls the shared package and creates a lambda and a layer which is then deployed in an application account
This would be used to support a public APG with code hosted in this repo.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2023-03-01 21:55 UTC, indrora requested changes
Almost there. Needs some work with IAM policies.

2023-03-01 21:55 UTC, indrora commented on python/cross-region-codeartifact/README.md
> +In this guide we will will provide a demo on how to utilize AWS CodePipeline via AWS CodeBuild to build and publish an artifact to CodeArtifact and then consume the built artifact in another CodePipe
Rewrite this in the form of "In this example, you will use AWS CodePipeline via AWS CodeBuild to build and publish and artifact..."

Include information on how customers can see the effects of the example as it does its thing. 

Include information on the usage of CDK Nags.

2023-03-01 21:55 UTC, indrora commented on python/cross-region-codeartifact/README.md
> +```
Explain what happens next. Explain how to interact with the deployed infrastructure.

2023-03-01 21:55 UTC, indrora commented on python/cross-region-codeartifact/app.py
> +# adding cdk nag checks
Expand this comment for someone who doesn't know.

2023-03-01 21:55 UTC, indrora commented on python/cross-region-codeartifact/cdk/helpers/pipeline_common.py
> +def update_role_with_codeartifact_policy(
Please rewrite this to use grant functions where possible. 

Please scope this as far down as possible where not using wildcards. 

We *highly* suggest against the use of raw IAM policies where role grants are more appropriate.

2023-03-07 21:35 UTC, kareem-rady commented
Changes have been added as requested

2023-03-20 21:21 UTC, indrora commented
These changes don't really cover the comments and changes I've requested. In places where more information has been requested, little has changed. I asked for explanations as to why you aren't using grant_x calls (since you're working with L1 constructs, you don't have grant_x calls) and nothing exists in the README nor in the comments around it. 

Code quality wise, this doesn't pass a second or third read. You're generating ARNs by hand, which is a huge red flag in my opinion: You should be able to reference the resources directly across stacks without generating ARNs by hand; in cases with circular dependencies, references by name should be used where a direct reference isn't reasonable. Where an ARN is needed for a reference, use the appropriate call, such as [the ARN of a role](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#rolearn). 

There's very little documentation on what this code does. There's very little documentation on why this code does. The README does not clarify how the customer can use this and observe it working. 

I'm going to close this PR here. Feel free to clean this up and open a new PR.

2023-03-20 21:21 UTC, closed without merging