AWS CDK Go Sample - ECS Cluster With ALB
aws-samples/aws-cdk-examples pull request #812
Opened 2023-03-10 22:37 UTC by yaseenyounus

# Overview
* Adds a new CDK Go sample that demonstrates how to configure and deploy an ECS Cluster with an Application Load Balancer (ALB). 
* Provides a README with deployment and testing guidance.
* Contains custom Go tests for the infrastructure / stack being deployed.

---

Fixes #811 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2023-03-14 19:40 UTC, indrora requested changes
Improve the readme and it looks good to me.

2023-03-14 19:40 UTC, indrora commented on go/ecs/cluster-alb/README.md
> +- Navigate to the AWS console and view the services that were deployed in the VPC (Subnets, Route Tables, etc), ECS (Cluster, Service, Task Definition, etc) and EC2 (Load Balancer, Target Groups, etc
* How can the customer see that the ALB is being used? 
* How can the customer enable TLS?
* What actions can the customer take to extend this?

2023-03-14 19:40 UTC, indrora commented on go/ecs/cluster-alb/README.md
> +This is useful because traffic will not directly hit the ECS cluster; rather, it will be routed through the ALB to access the application.
Give a real-world example of where this would make sense to use.

2023-03-14 22:17 UTC, yaseenyounus commented
> Improve the readme and it looks good to me.

Thanks for the suggestions @indrora. Please let me know your thoughts on the README updates. Thanks!

2023-03-16 21:41 UTC, indrora submitted a review, later dismissed
Some suggestions to clear up the language. 

I'll rubber stamp these minor edits.

2023-03-16 21:41 UTC, indrora commented on go/ecs/cluster-alb/README.md
> +Imagine we are running a containerized application with multiple tasks within an ECS Cluster service. We wouldn't want to expose the service directly to the internet as part of security best practice
```suggestion
When running a containerized application with multiple tasks in an ECS Cluster service, not exposing the service directly to the internet as part of security best practices. In this example, we deploy an Application Load Balancer (ALB) in front of the service to both balance traffic, and act as the single point of entry to the application.
```

2023-03-16 21:41 UTC, indrora commented on go/ecs/cluster-alb/README.md
> +- Protect your ALB from attacks and malicious traffic using [Web Application Firewall (WAF)](https://docs.aws.amazon.com/waf/latest/developerguide/waf-chapter.html).
```suggestion
## Further Improvements

This example does not use an HTTPS listener. For improved security, HTTPS (TLS) is encouraged. Some further improvements that can be made are:

- Enable TLS at the ALB by [creating an HTTPS listener](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#add-https-listener).
- Use a [CloudFront distribution to cache results returned from the application](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistS3AndCustomOrigins.html#concept_elb_origin), reducing load on the containerized application overall.
- Route traffic to the ALB with a [custom Route 53 domain](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html).
- Protect your ALB from attacks and malicious traffic using [Web Application Firewall (WAF)](https://docs.aws.amazon.com/waf/latest/developerguide/waf-chapter.html).
```

2023-03-16 23:00 UTC, indrora approved these changes

2023-03-16 23:25 UTC, indrora approved these changes

2023-03-16 23:25 UTC, merged