chore: Update Typescript to 5.1.6 and ts-node to 10.9.1
aws-samples/aws-cdk-examples pull request #901
Opened 2023-08-03 14:51 UTC by markusl

Update Typescript to 5.1.6 and ts-node to 10.9.1

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2023-08-03 15:44 UTC, ericzbeard approved these changes

2023-08-03 15:48 UTC, ericzbeard requested changes
The build is failing.

2023-08-03 18:37 UTC, markusl commented
I had to fix a number of small issues since many of the projects are a bit out-of-date. The build is passing now

2023-08-07 16:12 UTC, ericzbeard approved these changes

2023-08-07 16:13 UTC, merged