Example for ImageBuilder build pipeline for amazon linux 2023
aws-samples/aws-cdk-examples pull request #987
Opened 2024-01-23 14:48 UTC by hamadsuniverse

Added an example project that demonstrates how to create an ImageBuilder pipeline to build a container image using Amazon Linux 2023 base image and installing git, docker and nodejs in it so it can be used in building pipelines such as in Amazon CodeCatalyst.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2024-02-05 01:39 UTC, kaizio requested changes
Requested a couple of changes. Thanks for the add.

2024-02-05 01:39 UTC, kaizio commented on typescript/imagebuilder/bin/imagebuilder-components/docker.yaml
This file is installing docker not git. Check names used in the file.

2024-02-05 01:39 UTC, kaizio commented on typescript/imagebuilder/lib/imagebuilder-stack.ts
Can you add comments for this file so that the reader knows what is happening.

2024-02-05 01:41 UTC, kaizio commented
Also `npm run --if-present test` is failing in the build checks.

2024-02-13 14:15 UTC, hamadsuniverse commented
Actioned all points and build/all checks are passing. Pending your review and merge. Thanks!

2024-02-18 15:02 UTC, kaizio approved these changes

2024-02-18 15:02 UTC, merged