feat(python): adding example for s3, athena and glue
aws-samples/aws-cdk-examples pull request #988
Opened 2024-01-25 15:01 UTC by paulosergio-jnr

Fixes #766 

Adding example for S3, Athena and Glue

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2024-02-05 01:48 UTC, kaizio requested changes
Requested some comments on the main file. Thanks for the add!

2024-02-05 01:48 UTC, kaizio commented on python/athena-s3-glue/athena_s3_glue/athena_s3_glue_stack.py
Can you add comments to this file so that we know what is happening?

2024-02-12 14:24 UTC, paulosergio-jnr commented on python/athena-s3-glue/athena_s3_glue/athena_s3_glue_stack.py
Done. Thank you for the comment

2024-02-18 15:03 UTC, kaizio approved these changes

2024-02-18 15:04 UTC, kaizio approved these changes

2024-02-18 16:11 UTC, merged